package com.oceangrsmith.mylockerapplication.utility


const val PIN_FRAGMENT_DATA = "PIN FRAGMENT DATA"
const val PIN_NAVIGATION_KEY = "PIN NAVIGATION KEY"
const val I_HAVE_PIN = "I HAVE PIN"
const val NO_PIN = "NO PIN"
const val PICK_A_PACKAGE = "PICK A PACKAGE"
const val DELIVER_A_PACKAGE = "DELIVER A PACKAGE"
const val I_HAVE_AN_ACCOUNT = "I HAVE AN ACCOUNT"
const val DETAILS_OF_PACKAGES_AVAILABLE = "DETAILS OF PACKAGES AVAILABLE"